modLoader = "javafml" #mandatory
loaderVersion = "${neoforge_loader_version_range}" #mandatory
license = "${license}" # Review your options at https://choosealicense.com/.
issueTrackerURL = "https://github.com/WinsomeGuy/Cascades-Cool-Biomes/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "https://modrinth.com/mod/cascades-cool-biomes"
logoFile = "pack.png"
credits = "${credits}"
authors = "${mod_author}"
description = '''${description}'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "mr_hybrid_beta"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "wwoo"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "t_and_t"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "BOTH"